### ISSUE TITLE
Add support for ng-annotate

### ISSUE THREAD

**Issue by leosuncin** [opus-online/angular-seed#7]
In order to avoid errors due minify in production, you can use [ng-annotate-webpack-plugin](https://github.com/jeffling/ng-annotate-webpack-plugin)

```
npm i -S ng-annotate-webpack-plugin
```

```js
// webpack.config.js
/**
 * Webpack plugins
 */
const NgAnnotatePlugin = require('ng-annotate-webpack-plugin')

const config = {
...
  plugins: [
    ...
    new NgAnnotatePlugin({
      add: true,
    }),
  ],
}
...
if (process.env.NODE_ENV === 'production') {
    config.plugins.push(new webpack.optimize.UglifyJsPlugin({
      output: {
        comments: false,
      },
      compress: {
        drop_console: true,
        warnings: false,
      },
      mangle: true,
    }));
}
...
```
And add annotation comment on source files, by example `src/configs/routing/index.js`
```js
/* @ngInject */
export default ($locationProvider, $urlRouterProvider) => {
  $locationProvider.html5Mode({
    enabled: true,
    requireBase: false,
  })
  $urlRouterProvider.otherwise('/home')
}
```

**Comment by peeter-tomberg** [comment]
We went another route, simply not mangling variables in our application (we still minify the code, we simply dont change the variable names in our application production build). It does penalize a bit, but more often than not we simply forgot the @ngInject annotation and broke builds in our demo environment when everything worked fine in our dev environment. 

You're welcome to make a PR though.
